# Generated by Django 5.0.1 on 2024-03-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_delete_user'),
        ('libraryApp', '0003_alter_book_genre'),
    ]

    operations = [
    ]
