# Generated by Django 5.0.1 on 2024-03-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0004_merge_0002_delete_user_0003_alter_book_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('book_title', models.CharField(max_length=70)),
                ('book_author', models.CharField(max_length=70)),
            ],
        ),
    ]
