# Generated by Django 5.0.1 on 2024-04-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0005_book_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
    ]
